### ISSUE TITLE
Failed to fetch link content ...

### ISSUE THREAD

**Issue by ItsNoted** [hoarder-app/hoarder#199]
What's the main cause of this error? "Failed to fetch link content ..."

I am running the latest docker image and it will not fetch any of the content for any link I add.

My first thought was a permission issue but not sure where.

Then I saw these errors.

```
workers_1      | 2024-06-06T12:37:26.867Z error: [Crawler][14] Crawling job failed: SqliteError: no such table: bookmarks
```

```
}
s [TRPCError]: UNAUTHORIZED
    at /app/apps/web/.next/server/chunks/838.js:1:6145
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async c.middlewares (/app/apps/web/.next/server/chunks/673.js:4823:10163)
    at async a (/app/apps/web/.next/server/chunks/673.js:4823:9557)
    at async t (/app/apps/web/.next/server/chunks/673.js:4823:8930)
    at async a (/app/apps/web/.next/server/chunks/673.js:4823:9557)
    at async a (/app/apps/web/.next/server/chunks/673.js:4823:9557)
    at async a (/app/apps/web/.next/server/chunks/673.js:4823:9557)
    at async t (/app/apps/web/.next/server/chunks/673.js:4823:9896)
    at async /app/apps/web/.next/server/app/api/trpc/[trpc]/route.js:1:4281 {
  code: 'UNAUTHORIZED',
  [cause]: undefined
}
s [TRPCError]: UNAUTHORIZED
    at /app/apps/web/.next/server/chunks/838.js:1:6145
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async c.middlewares (/app/apps/web/.next/server/chunks/673.js:4823:10163)
    at async a (/app/apps/web/.next/server/chunks/673.js:4823:9557)
    at async t (/app/apps/web/.next/server/chunks/673.js:4823:8930)
    at async a (/app/apps/web/.next/server/chunks/673.js:4823:9557)
    at async a (/app/apps/web/.next/server/chunks/673.js:4823:9557)
    at async a (/app/apps/web/.next/server/chunks/673.js:4823:9557)
    at async t (/app/apps/web/.next/server/chunks/673.js:4823:9896)
    at async /app/apps/web/.next/server/app/api/trpc/[trpc]/route.js:1:4281 {
  code: 'UNAUTHORIZED',
  [cause]: undefined
}
s [TRPCError]: UNAUTHORIZED
    at /app/apps/web/.next/server/chunks/838.js:1:6145
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async c.middlewares (/app/apps/web/.next/server/chunks/673.js:4823:10163)
    at async a (/app/apps/web/.next/server/chunks/673.js:4823:9557)
    at async t (/app/apps/web/.next/server/chunks/673.js:4823:8930)
    at async a (/app/apps/web/.next/server/chunks/673.js:4823:9557)
    at async a (/app/apps/web/.next/server/chunks/673.js:4823:9557)
    at async a (/app/apps/web/.next/server/chunks/673.js:4823:9557)
    at async t (/app/apps/web/.next/server/chunks/673.js:4823:9896)
    at async /app/apps/web/.next/server/app/api/trpc/[trpc]/route.js:1:4281 {
  code: 'UNAUTHORIZED',
  [cause]: undefined
}
s [TRPCError]: UNAUTHORIZED
    at /app/apps/web/.next/server/chunks/838.js:1:6145
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async c.middlewares (/app/apps/web/.next/server/chunks/673.js:4823:10163)
    at async a (/app/apps/web/.next/server/chunks/673.js:4823:9557)
    at async t (/app/apps/web/.next/server/chunks/673.js:4823:8930)
    at async a (/app/apps/web/.next/server/chunks/673.js:4823:9557)
    at async a (/app/apps/web/.next/server/chunks/673.js:4823:9557)
    at async a (/app/apps/web/.next/server/chunks/673.js:4823:9557)
    at async t (/app/apps/web/.next/server/chunks/673.js:4823:9896)
    at async /app/apps/web/.next/server/app/api/trpc/[trpc]/route.js:1:4281 {
  code: 'UNAUTHORIZED',
  [cause]: undefined
}
s [TRPCError]: UNAUTHORIZED
    at /app/apps/web/.next/server/chunks/838.js:1:6145
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async c.middlewares (/app/apps/web/.next/server/chunks/673.js:4823:10163)
    at async a (/app/apps/web/.next/server/chunks/673.js:4823:9557)
    at async t (/app/apps/web/.next/server/chunks/673.js:4823:8930)
    at async a (/app/apps/web/.next/server/chunks/673.js:4823:9557)
    at async a (/app/apps/web/.next/server/chunks/673.js:4823:9557)
    at async a (/app/apps/web/.next/server/chunks/673.js:4823:9557)
    at async t (/app/apps/web/.next/server/chunks/673.js:4823:9896)
    at async /app/apps/web/.next/server/app/api/trpc/[trpc]/route.js:1:4281 {
  code: 'UNAUTHORIZED',
  [cause]: undefined
}
```
Also seeing this.

```
[0606/010650.554000:INFO:policy_logger.cc(145)] :components/policy/core/common/config_dir_policy_loader.cc(118) Skipping recommended platform policies because no policy file was found at: /etc/chromium/policies/recommended
[0606/012150.643036:INFO:policy_logger.cc(145)] :components/policy/core/common/config_dir_policy_loader.cc(118) Skipping mandatory platform policies because no policy file was found at: /etc/chromium/policies/managed
[0606/012150.643058:INFO:policy_logger.cc(145)] :components/policy/core/common/config_dir_policy_loader.cc(118) Skipping recommended platform policies because no policy file was found at: /etc/chromium/policies/recommended
[0606/013650.734295:INFO:policy_logger.cc(145)] :components/policy/core/common/config_dir_policy_loader.cc(118) Skipping mandatory platform policies because no policy file was found at: /etc/chromium/policies/managed
[0606/013650.734315:INFO:policy_logger.cc(145)] :components/policy/core/common/config_dir_policy_loader.cc(118) Skipping recommended platform policies because no policy file was found at: /etc/chromium/policies/recommended
[0606/015150.834569:INFO:policy_logger.cc(145)] :components/policy/core/common/config_dir_policy_loader.cc(118) Skipping mandatory platform policies because no policy file was found at: /etc/chromium/policies/managed
[0606/015150.834589:INFO:policy_logger.cc(145)] :components/policy/core/common/config_dir_policy_loader.cc(118) Skipping recommended platform policies because no policy file was found at: /etc/chromium/policies/recommended
[0606/020650.934375:INFO:policy_logger.cc(145)] :components/policy/core/common/config_dir_policy_loader.cc(118) Skipping mandatory platform policies because no policy file was found at: /etc/chromium/policies/managed
[0606/020650.934392:INFO:policy_logger.cc(145)] :components/policy/core/common/config_dir_policy_loader.cc(118) Skipping recommended platform policies because no policy file was found at: /etc/chromium/policies/recommended
[0606/022151.034385:INFO:policy_logger.cc(145)] :components/policy/core/common/config_dir_policy_loader.cc(118) Skipping mandatory platform policies because no policy file was found at: /etc/chromium/policies/managed
[0606/022151.034406:INFO:policy_logger.cc(145)] :components/policy/core/common/config_dir_policy_loader.cc(118) Skipping recommended platform policies because no policy file was found at: /etc/chromium/policies/recommended
[0606/023651.126071:INFO:policy_logger.cc(145)] :components/policy/core/common/config_dir_policy_loader.cc(118) Skipping mandatory platform policies because no policy file was found at: /etc/chromium/policies/managed
[0606/023651.126092:INFO:policy_logger.cc(145)] :components/policy/core/common/config_dir_policy_loader.cc(118) Skipping recommended platform policies because no policy file was found at: /etc/chromium/policies/recommended
[0606/025151.226394:INFO:policy_logger.cc(145)] :components/policy/core/common/config_dir_policy_loader.cc(118) Skipping mandatory platform policies because no policy file was found at: /etc/chromium/policies/managed
[0606/025151.226415:INFO:policy_logger.cc(145)] :components/policy/core/common/config_dir_policy_loader.cc(118) Skipping recommended platform policies because no policy file was found at: /etc/chromium/policies/recommended
```

**Comment by kamtschatka** [comment]
does your hoarder-worker not have access to the database? did you set all environment variables correctly and attached all the volumes?

**Comment by ItsNoted** [comment]
I think it was because the worker dir was not the same as the web dir. Seems to be working now so far.

**Comment by ItsNoted** [comment]
Closing this as it appears to be fixed :)
