### ISSUE TITLE
npm error

### ISSUE THREAD

**Issue by mcking230** [hoarder-app/hoarder#217]
Cant run application on Ubuntu 22.04.4

```
root@zm:/home/zm# hoarder
file:///usr/local/lib/node_modules/@hoarderapp/cli/dist/index.mjs:1226
    method: opts.methodOverride ?? METHOD[type],
                                 ^

SyntaxError: Unexpected token '?'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)
root@zm:/home/zm# 
```

**Comment by mcking230** [comment]
Problem solved! Updated latest version manually, thanks!
