### ISSUE TITLE
SQLite Bookmark Table Issue

### ISSUE THREAD

**Issue by digitalwm** [hoarder-app/hoarder#234]
Version: Fresh Install on 18.06.2024 - latest version
Docker Install - based on the configuration example from the docu.

Database File is there and I can access it.

/app/apps/workers/node_modules/.pnpm/better-sqlite3@9.4.3/node_modules/better-sqlite3/lib/methods/wrappers.js:5
workers-1      |        return this[cppdb].prepare(sql, this, false);
workers-1      |                           ^
workers-1      | SqliteError: no such table: bookmarkLinks
workers-1      |     at Database.prepare (/app/apps/workers/node_modules/.pnpm/better-sqlite3@9.4.3/node_modules/better-sqlite3/lib/methods/wrappers.js:5:21)
workers-1      |     at BetterSQLiteSession.prepareQuery (/app/apps/workers/node_modules/.pnpm/drizzle-orm@0.29.4_better-sqlite3@9.4.3/node_modules/drizzle-orm/better-sqlite3/session.cjs:42:30)
workers-1      |     at BetterSQLiteSession.prepareOneTimeQuery (/app/apps/workers/node_modules/.pnpm/drizzle-orm@0.29.4_better-sqlite3@9.4.3/node_modules/drizzle-orm/sqlite-core/session.cjs:91:17)
workers-1      |     at QueryPromise._prepare (/app/apps/workers/node_modules/.pnpm/drizzle-orm@0.29.4_better-sqlite3@9.4.3/node_modules/drizzle-orm/sqlite-core/query-builders/update.cjs:101:81)
workers-1      |     at QueryPromise.run (/app/apps/workers/node_modules/.pnpm/drizzle-orm@0.29.4_better-sqlite3@9.4.3/node_modules/drizzle-orm/sqlite-core/query-builders/update.cjs:111:17)
workers-1      |     at QueryPromise.execute (/app/apps/workers/node_modules/.pnpm/drizzle-orm@0.29.4_better-sqlite3@9.4.3/node_modules/drizzle-orm/sqlite-core/query-builders/update.cjs:123:54)
workers-1      |     at QueryPromise.then (/app/apps/workers/node_modules/.pnpm/drizzle-orm@0.29.4_better-sqlite3@9.4.3/node_modules/drizzle-orm/query-promise.cjs:44:17)
workers-1      |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
workers-1      |   code: 'SQLITE_ERROR'
workers-1      | }

**Comment by digitalwm** [comment]
Realized that the workers and the hoarder share the volume and this is how they use the database. Fixed it in my docker compose config.
