### ISSUE TITLE
Documentation to properly configure SSL certificates

### ISSUE THREAD

**Issue by schiffy91** [hoarder-app/hoarder#369]
IIUC, the documentation doesn't specify where to place my SSL related files (i.e. `fullchain.pem`, `privkey.pem`). They're located at `/Users/server/Documents/ssl/` on my server, and I mount them in the web docker container at `/etc/ssl/certs` by specifying this directory in `services:web:volumes` in `docker-compose.yaml`. Unfortunately, I'm unable to connect to the website over HTTPS, but I can connect to the website over HTTP. However, I cannot login over HTTP – I get an error.

When I try and reach the website over HTTPs, Chrome gives me the following error on my clients

```
This site can’t provide a secure connection
REDACTED sent an invalid response.
ERR_SSL_PROTOCOL_ERROR
```

When I try and login over HTTP, the client shows a red error (`fetch failed`) and the relevant docker logs give the following error

```
2024-09-01 13:23:16 web-1          | [next-auth][error][CLIENT_FETCH_ERROR] 
2024-09-01 13:23:16 web-1          | https://next-auth.js.org/errors#client_fetch_error fetch failed {
2024-09-01 13:23:16 web-1          |   error: {
2024-09-01 13:23:16 web-1          |     message: 'fetch failed',
2024-09-01 13:23:16 web-1          |     stack: 'TypeError: fetch failed\n' +
2024-09-01 13:23:16 web-1          |       '    at node:internal/deps/undici/undici:12500:13\n' +
2024-09-01 13:23:16 web-1          |       '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
2024-09-01 13:23:16 web-1          |       '    at async globalThis.fetch (/app/apps/web/.next/server/chunks/369.js:1:36492)',
2024-09-01 13:23:16 web-1          |     name: 'TypeError'
2024-09-01 13:23:16 web-1          |   },
2024-09-01 13:23:16 web-1          |   url: 'https://REDACTED.com:3000/api/auth/providers',
2024-09-01 13:23:16 web-1          |   message: 'fetch failed'
2024-09-01 13:23:16 web-1          | }
2024-09-01 13:46:57 web-1          | [next-auth][error][CLIENT_FETCH_ERROR] 
2024-09-01 13:46:57 web-1          | https://next-auth.js.org/errors#client_fetch_error fetch failed {
2024-09-01 13:46:57 web-1          |   error: {
2024-09-01 13:46:57 web-1          |     message: 'fetch failed',
2024-09-01 13:46:57 web-1          |     stack: 'TypeError: fetch failed\n' +
2024-09-01 13:46:57 web-1          |       '    at node:internal/deps/undici/undici:12500:13\n' +
2024-09-01 13:46:57 web-1          |       '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
2024-09-01 13:46:57 web-1          |       '    at async globalThis.fetch (/app/apps/web/.next/server/chunks/369.js:1:36492)',
2024-09-01 13:46:57 web-1          |     name: 'TypeError'
2024-09-01 13:46:57 web-1          |   },
2024-09-01 13:46:57 web-1          |   url: 'https://REDACTED.com:3000/api/auth/providers',
2024-09-01 13:46:57 web-1          |   message: 'fetch failed'
2024-09-01 13:46:57 web-1          | }
```

When I navigate to `https://REDACTED.com:3000/api/auth/providers`, I get the following error on Chrome:

```
This site can’t provide a secure connection
REDACTED.com sent an invalid response.
ERR_SSL_PROTOCOL_ERROR
```

My `docker-compose.yaml` looks like this

```
version: "3.8"
services:
  web:
    image: ghcr.io/hoarder-app/hoarder:${HOARDER_VERSION:-release}
    restart: unless-stopped
    volumes:
      - data:/data
      - /Users/server/Documents/ssl/:/etc/ssl/certs/
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      MEILI_ADDR: http://meilisearch:7700
      BROWSER_WEB_URL: http://chrome:9222
      # OPENAI_API_KEY: ...
      DATA_DIR: /data
  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:123
    restart: unless-stopped
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
  meilisearch:
    image: getmeili/meilisearch:v1.6
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MEILI_NO_ANALYTICS: "true"
    volumes:
      - meilisearch:/meili_data

volumes:
  meilisearch:
  data:
```

My `.env` looks like this

```
HOARDER_VERSION=release
NEXTAUTH_SECRET=REDACTED
MEILI_MASTER_KEY=REDACTED
NEXTAUTH_URL=https://REDACTED.com:3000
OPENAI_API_KEY=REDACTED
DISABLE_SIGNUPS=true
```

It'd be great to get some help. It seems like I've misconfigured the SSL certificates one way or another. Depending on the solution, I wonder if it would be helpful to update the documentation as well.

**Comment by MohamedBassem** [comment]
Hi, thanks for reaching out. If you want https (and you definitely should), you'll want to put Hoarder behind a reverse proxy (e.g. nginx, trafik, caddy, etc). Hoarder itself doesn't know how to deal with certs and the server only serves http requests.

**Comment by MohamedBassem** [comment]
As for logging in, if you want it to work over http, you'll want your `NEXTAUTH_URL` URL to also be an http URL (which doesn't seem to be the case from your error message). Currently, it seems to be pointing to your https URL which until now is not properly configured.

**Comment by schiffy91** [comment]
Ah, this would explain why I've been struggling to make this work. What would be the easiest way to put Hoarder behind a reverse proxy like nginx? It's been years since I've done that!

**Comment by MohamedBassem** [comment]
If you haven't done this in a while, [NginxProxyManager](https://nginxproxymanager.com/) is quite easy to setup and use.

**Comment by MohamedBassem** [comment]
Closing this for now given that it's out of the scope of what hoarder offers.
