### ISSUE TITLE
inference job failed

### ISSUE THREAD

**Issue by hujh818** [hoarder-app/hoarder#424]
2024-09-25T03:12:13.473Z info: [inference][15] Starting an inference job for bookmark with id "z3nf9s85x282vcvf42pp7v9u"
2024-09-25T03:12:14.911Z info: [inference][15] Starting an inference job for bookmark with id "z3nf9s85x282vcvf42pp7v9u"
2024-09-25T03:12:16.418Z info: [inference][15] Starting an inference job for bookmark with id "z3nf9s85x282vcvf42pp7v9u"
2024-09-25T03:12:17.703Z error: [inference][15] inference job failed: TypeError: Cannot read properties of undefined (reading '0')

**Comment by kamtschatka** [comment]
Please explain what you did and what you checked.
Is this a link bookmark or a text bookmark?
is your Meilisearch connected and working? 
Does it work for other bookmarks and only a specific one is failing, or is this happening all the time?

**Comment by Diew** [comment]
for me it happen all the time after update  1-2 day ago (maybe ? im not sure but it like have update on portainer)

then i try to test by start fresh and it still happen on both text and url

everything work fine but when it try to do inference job in log it error like first post guy

test on nearly default docker compose but change

OPENAI_API_KEY
NEXTAUTH_SECRET
MEILI_MASTER_KEY
and add 
OPENAI_BASE_URL
for openrouter

english not my native hope you can understand what im saying

![Screenshot 2024-09-26 at 01-17-08 Portainer docker-web](https://github.com/user-attachments/assets/fbe430fe-5f63-492b-8bf2-df4b09858893)

![Screenshot 2024-09-26 at 01-17-22 Hoarder](https://github.com/user-attachments/assets/d48da2c2-9741-4b08-82a5-227d6e29202b)

**Comment by kamtschatka** [comment]
Unfortunately the logging does not show where the issue happens. I have added better logging, once that is merged, you'll have to change your deployment to use the "latest" docker container and we'll see where the error actually happens.

**Comment by hujh818** [comment]
> Please explain what you did and what you checked. Is this a link bookmark or a text bookmark? is your Meilisearch connected and working? Does it work for other bookmarks and only a specific one is failing, or is this happening all the time?

1. a link bookmark 
2.  Meilisearch connected and working
3.  happening all the time

**Comment by hujh818** [comment]
> for me it happen all the time after update 1-2 day ago (maybe ? im not sure but it like have update on portainer)
> 
> then i try to test by start fresh and it still happen on both text and url
> 
> everything work fine but when it try to do inference job in log it error like first post guy
> 
> test on nearly default docker compose but change
> 
> OPENAI_API_KEY NEXTAUTH_SECRET MEILI_MASTER_KEY and add OPENAI_BASE_URL for openrouter
> 
> english not my native hope you can understand what im saying
> 
> ![Screenshot 2024-09-26 at 01-17-08 Portainer docker-web](https://private-user-images.githubusercontent.com/6524351/370847892-fbe430fe-5f63-492b-8bf2-df4b09858893.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczMTY4NDQsIm5iZiI6MTcyNzMxNjU0NCwicGF0aCI6Ii82NTI0MzUxLzM3MDg0Nzg5Mi1mYmU0MzBmZS01ZjYzLTQ5MmItOGJmMi1kZjRiMDk4NTg4OTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjZUMDIwOTA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTc5NzAwZTk1MmRiNjg5NTliODI5ZmUyMmU3YzIyMGNhNDU3MzUyNzM1MzM2ZTNiNTY4NzJiODNhOGJlYzNiYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.W_xgHq1Q6-SeVrpmxVJWA-AbhpkozOK16J1gwO0ZQeo)
> 
> ![Screenshot 2024-09-26 at 01-17-22 Hoarder](https://private-user-images.githubusercontent.com/6524351/370848025-d48da2c2-9741-4b08-82a5-227d6e29202b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczMTY4NDQsIm5iZiI6MTcyNzMxNjU0NCwicGF0aCI6Ii82NTI0MzUxLzM3MDg0ODAyNS1kNDhkYTJjMi05NzQxLTRiMDgtODJhNS0yMjdkNmUyOTIwMmIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjZUMDIwOTA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGUxYTA5NDk1MTcyMGE4NGY3NzBjMjVjYzY4YjlkNGRjZjdmYmZkMTU1MjMxMjFmMWMxZDYzN2ZkM2Q5NjQ1NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.-9sXCyc0d5j9Hz52hbUmlOu_7c1UBUvHiqTE-yfFED8)

i have set OPENAI_BASE_URL also

**Comment by hujh818** [comment]
TypeError: Cannot read properties of undefined (reading '0')

    at OpenAIInferenceClient.inferFromText (/app/apps/workers/inference.ts:2:2143)

    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

    at async inferTagsFromText (/app/apps/workers/openaiWorker.ts:32:158)

    at async inferTags (/app/apps/workers/openaiWorker.ts:32:375)

    at async Object.runOpenAI [as run] (/app/apps/workers/openaiWorker.ts:32:3805)

    at async Runner.runOnce (/app/apps/workers/node_modules/.pnpm/@hoarder+queue@file+packages+queue/node_modules/@hoarder/queue/runner.ts:2:2567)

I used the latest docker image, here is the detailed log

**Comment by kamtschatka** [comment]
ok seems to be this line:
```
    const response = chatCompletion.choices[0].message.content;
```
Are you using the real OpenAI or are you using something different? (Azure OpenAI was also reported as not working)
Unfortunately I do not have OpenAI, so I can't check, but maybe @MohamedBassem has more knowledge about this

**Comment by Diew** [comment]
i use openrouter
OPENAI_BASE_URL=https://openrouter.ai/api/v1

**Comment by kamtschatka** [comment]
hm i signed up for openrouter now and did not have any issues with it. Got a perfect response. Did you change the model to something different than the default maybe?

**Comment by hujh818** [comment]
> ok seems to be this line:
> 
> ```
>     const response = chatCompletion.choices[0].message.content;
> ```
> 
> Are you using the real OpenAI or are you using something different? (Azure OpenAI was also reported as not working) Unfortunately I do not have OpenAI, so I can't check, but maybe @MohamedBassem has more knowledge about this

i'm using a real OpenAI api with a different openai_base_url.

**Comment by hujh818** [comment]
maybe adding more logs to show error chat message?

**Comment by hujh818** [comment]
@kamtschatka 
i add one line to record the response of chatgpt

logger.info(`Response from OpenAI: ${chatCompletion}`);
here is the log:

2024-09-29T14:59:42.379Z info: Response from OpenAI: {"id":"chatcmpl-ACpgbQKnXKu72Hh1fGClWYy7DdSXk","object":"chat.completion","created":1727621981,"model":"gpt-4o-mini","choices":[{"index":0,"message":{"role":"assistant","content":"{\n  \"tags\": [\n    \"internet speed\",\n    \"broadband testing\",\n    \"network performance\",\n    \"technology\",\n    \"Ookla\"\n  ]\n}"},"logprobs":null,"finish_reason":"stop"}],"usage":{"prompt_tokens":423,"completion_tokens":35,"total_tokens":458},"system_fingerprint":"fp_878413d04d"}

2024-09-29T14:59:42.552Z info: [inference][16] Starting an inference job for bookmark with id "b1g3rlrdd5ds6augtn6wo7i7"

2024-09-29T14:59:43.873Z info: Response from OpenAI: {"id":"chatcmpl-ACpgdM5HAwwzdjhiE1uiH8whwifws","object":"chat.completion","created":1727621983,"model":"gpt-4o-mini","choices":[{"index":0,"message":{"role":"assistant","content":"{\n  \"tags\": [\n    \"Internet Speed Test\",\n    \"Broadband\",\n    \"Network Performance\",\n    \"Ookla\",\n    \"Connectivity\"\n  ]\n}"},"logprobs":null,"finish_reason":"stop"}],"usage":{"prompt_tokens":423,"completion_tokens":34,"total_tokens":457},"system_fingerprint":"fp_878413d04d"}

2024-09-29T14:59:44.066Z info: [inference][16] Starting an inference job for bookmark with id "b1g3rlrdd5ds6augtn6wo7i7"

2024-09-29T14:59:45.298Z info: Response from OpenAI: {"id":"chatcmpl-ACpgeImdD9s1kXvsHk3SPO88ZPFuF","object":"chat.completion","created":1727621984,"model":"gpt-4o-mini","choices":[{"index":0,"message":{"role":"assistant","content":"{\n  \"tags\": [\n    \"Internet Speed\",\n    \"Network Testing\",\n    \"Broadband\",\n    \"Ookla\",\n    \"Speedtest\"\n  ]\n}"},"logprobs":null,"finish_reason":"stop"}],"usage":{"prompt_tokens":423,"completion_tokens":34,"total_tokens":457},"system_fingerprint":"fp_878413d04d"}

2024-09-29T14:59:45.476Z info: [inference][16] Starting an inference job for bookmark with id "b1g3rlrdd5ds6augtn6wo7i7"

2024-09-29T14:59:46.650Z info: Response from OpenAI: {"id":"chatcmpl-ACpgga71hYeSscncX4FqHR9zz5tEo","object":"chat.completion","created":1727621986,"model":"gpt-4o-mini","choices":[{"index":0,"message":{"role":"assistant","content":"{\n  \"tags\": [\n    \"Internet\",\n    \"Broadband\",\n    \"Speed Test\",\n    \"Ookla\",\n    \"Network Performance\"\n  ]\n}"},"logprobs":null,"finish_reason":"stop"}],"usage":{"prompt_tokens":423,"completion_tokens":33,"total_tokens":456},"system_fingerprint":"fp_878413d04d"}

2024-09-29T14:59:46.650Z error: [inference][16] inference job failed: TypeError: Cannot read properties of undefined (reading '0')

TypeError: Cannot read properties of undefined (reading '0')

**Comment by kamtschatka** [comment]
@hujh818 are you able to come to discord? I am not sure if that is really what you got, or if github messed it up somehow. 
This response is not a valid JSON (due to "tags" being outside of the string) and if we were to talk in real time, we can probably analyze the issue a bit faster

**Comment by hujh818** [comment]
> @hujh818 are you able to come to discord? I am not sure if that is really what you got, or if github messed it up somehow. This response is not a valid JSON (due to "tags" being outside of the string) and if we were to talk in real time, we can probably analyze the issue a bit faster

ok, could you give me the discord link

**Comment by kamtschatka** [comment]
[it is on the readme](https://github.com/hoarder-app/hoarder)
![image](https://github.com/user-attachments/assets/d70b6c3e-02b1-45cc-b26f-6f146c1c3538)
top right button

**Comment by kamtschatka** [comment]
I was able to reproduce and fix the issue with @hujh818 and created a PR to fix this

**Comment by dossjjx** [comment]
Any update on what the was issue here? Was the PR merged?

**Comment by barthalion** [comment]
@hujh818 has never actually submitted a PR, fixed it only in their fork.
