### ISSUE TITLE
Updating docker compose documentation

### ISSUE THREAD

**Issue by Inventhrice** [hoarder-app/hoarder#580]
### Describe the Bug

This is me documenting my steps as I setup a dev environment for a Windows Machine.

1. `time="2024-10-22T16:20:51-04:00" level=warning msg="\\hoarder-dev\\hoarder\\docker\\docker-compose.dev.yml: `version` is obsolete"
env file \hoarder-dev\hoarder\docker\.env not found: CreateFile \hoarder-dev\hoarder\docker\.env: The system cannot find the file specified.`

The instructions on [the website](https://docs.hoarder.app/Development/setup/) says to `Start by copying the template by cp .env.sample .env.` If we want this to be true, then we should change the docker-compose.dev.yaml to look one directory above.

2. So far I am seeing a lot of `Progress: resolved 0, reused 0, downloaded 442, added 456`. Will keep updated on if this is expected.

If I have understood this correctly, apparently this step is ` Corepack is about to download https://registry.npmjs.org/pnpm/-/pnpm-9.0.0-alpha.8.tgz`. It looks like it is installing 3121 packages. Just noting here that this is giving my laptop a RUN for it's money, fans are spinning lol.

i was right 😄 

3. I am waiting for some confirmation that I can start developing.

4. Upon navigation to localhost:3000, i got `Error: Cannot open database because the directory does not exist`

### Steps to Reproduce

ref above

### Expected Behaviour

N/A

### Device Details

Windows 11

### Exact Hoarder Version

v0.18.0

**Comment by Inventhrice** [comment]
4. Upon navigation to localhost:3000, i got `Error: Cannot open database because the directory does not exist`

![image](https://github.com/user-attachments/assets/01a41a3c-3387-4235-9e12-d421480762bb)

From `/packages/db/drizzle.config.ts`, we find:
```
const databaseURL = serverConfig.dataDir
  ? `${serverConfig.dataDir}/db.db`
  : "./db.db";
```
serverConfig.dataDir comes from ..\shared\config.ts. dataDir is defined at line 106 `    dataDir: val.DATA_DIR,`, which comes from line 45 `  DATA_DIR: z.string().default(""),` which comes from line 1 `import { z } from "zod";`.

what the heck is "zod".

I have `DATA_DIR=../hoarder-data/` in .env, and that does not seem to have worked.

### Note for Disabling Sign In's as per Issue 556
There seems to be variables called 
```
  DEMO_MODE: stringBool("false"),
  DEMO_MODE_EMAIL: z.string().optional(),
  DEMO_MODE_PASSWORD: z.string().optional(),
```
which could be repurposed to solve #556 ? I haven't looked into it though

**Comment by MohamedBassem** [comment]
did you symlink the '.env' file to the apps/web directory? You need to do that and then run the db migrations.

**Comment by MohamedBassem** [comment]
oh, you're using the dev docker compose. Those instructions are for non-docker dev.

In the docker dev setup. The data dir should point to the dir inside the container. You can mount a volume at the same place if you want persistence.

**Comment by Inventhrice** [comment]
Note for Disabling Sign In's as per Issue 556
There seems to be variables called 
```
  DEMO_MODE: stringBool("false"),
  DEMO_MODE_EMAIL: z.string().optional(),
  DEMO_MODE_PASSWORD: z.string().optional(),
```
which could be repurposed to solve #556 ? I haven't looked into it though

**Comment by Inventhrice** [comment]
Okay, I am at a complete loss. I am getting a `TypeError: Cannot open database because the directory does not exist` error, which is not particularly helpful, as I do not know what it thinks the directory is. Touching base with the discord now.

**Comment by Inventhrice** [comment]
Trying `docker-compose -f docker/docker-compose.dev.yml up --build` as suggested from the discord

THAT WORKED. OKAY THEN!! Massive shoutout to for coming in clutch there!

**Comment by imaron85** [comment]
> fresh install (this is my first try at hoarder) added to my docker-compose.yml and the web service won't start with a similar error, I'm not using the docker-compose.dev.yml file (I'm following the instructions here: https://docs.hoarder.app/Installation/docker/)
> 
> "Running db migration script s6-rc: info: service fix-attrs successfully started s6-rc: info: service legacy-cont-init: starting s6-rc: info: service legacy-cont-init successfully started /db_migrations/index.js:811 throw new TypeError('Cannot open database because the directory does not exist'); ^
> 
> TypeError: Cannot open database because the directory does not exist at new Database (/db_migrations/index.js:811:9) at /db_migrations/index.js:11751:16 at /db_migrations/index.js:11825:3 at Object. (/db_migrations/index.js:11828:12) at Module._compile (node:internal/modules/cjs/loader:1546:14) at Object..js (node:internal/modules/cjs/loader:1689:10) at Module.load (node:internal/modules/cjs/loader:1318:32) at Function._load (node:internal/modules/cjs/loader:1128:12) at TracingChannel.traceSync (node:diagnostics_channel:315:14) at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
> 
> Node.js v22.11.0 s6-rc: warning: unable to start service init-db-migration: command exited 1"

I can second this. I tried to deploy a new instance to coolify via the services tab. Create the service, change .env variable and am getting the same error.

**Comment by NeoMod** [comment]
I'm leaving this here for anyone reaching this issue via google:

**The "cannot open database because the directory does not exist" issue derives from editing the "DATA_DIR" env.**

The default _docker-compose.yml_ example could benefit from a comment (something like #DO NOT EDIT near the line) or maybe it's just me assuming that an ENV could be edited.  Anyway, **do not edit the** _DATA_DIR: /data_ declaration when deploying.
