### ISSUE TITLE
SqliteError: no such table: user

### ISSUE THREAD

**Issue by meng8131** [hoarder-app/hoarder#768]
### Describe the Bug

I'm trying to deploy hoarder on Zeabur, after installed below services, hit error when trying to signup the first account.

**I'm fresh with coding, and did this with help of Claude, thanks for any advices.**

# services installed

<img width="225" alt="image" src="https://github.com/user-attachments/assets/57bfd801-2077-42e6-b4d8-4982f29321af" />

# error shown  at signup page

<img width="337" alt="image" src="https://github.com/user-attachments/assets/cc419947-ac9a-4e54-ac4b-f38731378766" />

# error log shown in Zeabur server log

SqliteError: no such table: user

    at Database.prepare (/app/node_modules/better-sqlite3/lib/methods/wrappers.js:5:21)

    ... 6 lines matching cause stack trace ...

    at process.processTicksAndRejections (node:internal/process/task_queues:105:5) {

  code: 'INTERNAL_SERVER_ERROR',

  name: 'TRPCError',

  [cause]: SqliteError: no such table: user

      at Database.prepare (/app/node_modules/better-sqlite3/lib/methods/wrappers.js:5:21)

      at v.prepareQuery (/app/apps/web/.next/server/chunks/3632.js:67:47379)

      at v.prepareOneTimeQuery (/app/apps/web/.next/server/chunks/3632.js:67:46284)

      at m._prepare (/app/apps/web/.next/server/chunks/3632.js:67:79635)

      at m.all (/app/apps/web/.next/server/chunks/3632.js:67:79820)

      at m.execute (/app/apps/web/.next/server/chunks/3632.js:67:79932)

      at m.then (/app/apps/web/.next/server/chunks/3632.js:67:57668)

      at process.processTicksAndRejections (node:internal/process/task_queues:105:5) {

    code: 'SQLITE_ERROR'

  }

}

### Steps to Reproduce

1. signup

### Expected Behaviour

how to fix the error

### Exact Hoarder Version

ghcr.io/hoarder-app/hoarder

**Comment by MohamedBassem** [comment]
Not sure what `Zeabur` is, but this usually means that the database got wiped. Did you change the storage of the container after starting it? Try restarting it, this should re run the database migrations.

**Comment by dionorgua** [comment]
I would say it's not 'wiped'. It's actually "not created". Most likely app has no permissions to create that database

**Comment by meng8131** [comment]
> Not sure what `Zeabur` is, but this usually means that the database got wiped. Did you change the storage of the container after starting it? Try restarting it, this should re run the database migrations.

@MohamedBassem 

hi, thanks for your reply.
zeabur is a PaaS service for full stack application deployment.
I re-deplyed Hoarder with below TOML config, looks good?  still hit the same "**code: 'INTERNAL_SERVER_ERROR'**" error


> name = "hoarder"
> 
> [source]
> image = "ghcr.io/hoarder-app/hoarder:latest"
> 
> [[volumes]]
> id = "data"
> dir = "/data"
> 
> [[volumes]]
> id = "meilidata"
> dir = "/meili_data"
> 
> [[ports]]
> id = "web"
> port = 3000
> type = "HTTP"
> 
> [env]
> HOARDER_VERSION = { default = "release" }
> NEXTAUTH_SECRET = { default = "HN9WXDZ8qdL0KH****" }  
> MEILI_MASTER_KEY = { default = "uahsEgSLRDebW****" } 
> NEXTAUTH_URL = { default = "https://***.zeabur.com" }     
>
> OPENAI_API_KEY = { default = "" }    # 可选，设置 OpenAI API key

**Comment by MohamedBassem** [comment]
@meng8131 Given that you're not using the docker compose file, you seem to be missing the `DATA_DIR` env variable that should point to `/data`.

**Comment by meng8131** [comment]
Thanks for your reply.
I have successfully redeployed using Zeabur's official template.

I am very happy to be able to use Hoarder in 2025. Thank you again for your contribution.


Hoarder @Zeabur FYI
https://zeabur.com/templates/EH3W1O
